import type { CatalogCategorySeed, CatalogProductSeed, MenuAreaSlug } from "@/lib/coffee/types";

export const COFFEE_SHOP_SLUG = "coffee-shop-main";

export const areaCategoryOrder: Record<MenuAreaSlug, string[]> = {
  foods: [
    "fried-savories",
    "baked-savories",
    "cheese-bread",
    "grilled-sandwiches",
    "savory-croissants",
    "sweet-croissants",
    "desserts",
    "tapiocas",
    "crepiocas",
  ],
  "hot-drinks": [
    "espresso-bar",
    "teas",
    "cappuccinos",
    "signature-hot-drinks",
    "chocolates",
  ],
  "cold-drinks": [
    "iced-coffees",
    "cold-teas-and-lemonade",
    "sodas",
    "cold-beverages",
    "juices-and-vitaminas",
    "milkshakes-and-frappes",
  ],
};

export const catalogCategories: CatalogCategorySeed[] = [
  {
    slug: "fried-savories",
    area: "foods",
    namePt: "Salgados Fritos",
    descriptionPt: "Clássicos de lanchonete servidos quentinhos e crocantes.",
    accentColor: "var(--tone-amber)",
    sortOrder: 10,
  },
  {
    slug: "baked-savories",
    area: "foods",
    namePt: "Salgados Assados",
    descriptionPt: "Opções assadas para um lanche mais leve, mas ainda bem recheado.",
    accentColor: "var(--tone-mocha)",
    sortOrder: 20,
  },
  {
    slug: "cheese-bread",
    area: "foods",
    namePt: "Pão de Queijo",
    descriptionPt:
      "Preparado todos os dias na Cafeteria AT com queijo de Minas, mantendo o sabor original da casa.",
    accentColor: "var(--tone-cream)",
    sortOrder: 30,
  },
  {
    slug: "grilled-sandwiches",
    area: "foods",
    namePt: "Mistos e Sanduíches",
    descriptionPt: "Lanches rápidos para balcão, totem ou mesa.",
    accentColor: "var(--tone-forest)",
    sortOrder: 40,
  },
  {
    slug: "savory-croissants",
    area: "foods",
    namePt: "Croissants Salgados",
    descriptionPt: "Sanduíches saborosos feitos com croissant amanteigado.",
    accentColor: "var(--tone-amber)",
    sortOrder: 50,
  },
  {
    slug: "sweet-croissants",
    area: "foods",
    namePt: "Croissants Doces",
    descriptionPt: "Versões doces para acompanhar o café ou fechar o pedido.",
    accentColor: "var(--tone-berry)",
    sortOrder: 60,
  },
  {
    slug: "desserts",
    area: "foods",
    namePt: "Sobremesas",
    descriptionPt: "Fatia de bolo caseiro para combinar com bebidas quentes.",
    accentColor: "var(--tone-berry)",
    sortOrder: 70,
  },
  {
    slug: "tapiocas",
    area: "foods",
    namePt: "Tapiocas",
    descriptionPt: "Opções salgadas e doces em massa leve, feitas na hora.",
    accentColor: "var(--tone-cream)",
    sortOrder: 80,
  },
  {
    slug: "crepiocas",
    area: "foods",
    namePt: "Crepiocas",
    descriptionPt: "Crepe de tapioca com ovos e crosta de queijo.",
    accentColor: "var(--tone-forest)",
    sortOrder: 90,
  },
  {
    slug: "espresso-bar",
    area: "hot-drinks",
    namePt: "Café Espresso e Métodos",
    descriptionPt:
      "Grãos 100% arábica do Sul de Minas e Cerrado, com perfil encorpado e aroma de chocolate.",
    accentColor: "var(--tone-mocha)",
    sortOrder: 10,
  },
  {
    slug: "teas",
    area: "hot-drinks",
    namePt: "Chás",
    descriptionPt: "Infusões quentes de 180 ml em sabores frutados.",
    accentColor: "var(--tone-forest)",
    sortOrder: 20,
  },
  {
    slug: "cappuccinos",
    area: "hot-drinks",
    namePt: "Cappuccinos",
    descriptionPt:
      "A clássica combinação italiana com leite vaporizado, chocolate e canela.",
    accentColor: "var(--tone-cream)",
    sortOrder: 30,
  },
  {
    slug: "signature-hot-drinks",
    area: "hot-drinks",
    namePt: "Especiais Quentes",
    descriptionPt: "Combinações da casa com café espresso e coberturas.",
    accentColor: "var(--tone-amber)",
    sortOrder: 40,
  },
  {
    slug: "chocolates",
    area: "hot-drinks",
    namePt: "Chocolates",
    descriptionPt: "Chocolate quente ou versões geladas intensas com Nutella e Ovomaltine.",
    accentColor: "var(--tone-berry)",
    sortOrder: 50,
  },
  {
    slug: "iced-coffees",
    area: "cold-drinks",
    namePt: "Cafés Gelados",
    descriptionPt: "Bebidas frias com café espresso, chantilly e sabores da casa.",
    accentColor: "var(--tone-mocha)",
    sortOrder: 10,
  },
  {
    slug: "cold-teas-and-lemonade",
    area: "cold-drinks",
    namePt: "Chás Gelados e Limonada",
    descriptionPt: "Opções refrescantes para pedidos rápidos ou retirada no balcão.",
    accentColor: "var(--tone-forest)",
    sortOrder: 20,
  },
  {
    slug: "sodas",
    area: "cold-drinks",
    namePt: "Sodas",
    descriptionPt: "Sabores artesanais servidos em copos de 400 ml.",
    accentColor: "var(--tone-berry)",
    sortOrder: 30,
  },
  {
    slug: "cold-beverages",
    area: "cold-drinks",
    namePt: "Bebidas",
    descriptionPt: "Geladeira completa com refrigerantes, energéticos, água e sucos prontos.",
    accentColor: "var(--tone-cream)",
    sortOrder: 40,
  },
  {
    slug: "juices-and-vitaminas",
    area: "cold-drinks",
    namePt: "Sucos e Vitaminas",
    descriptionPt: "Sucos naturais, polpas batidas e vitamina especial da casa.",
    accentColor: "var(--tone-amber)",
    sortOrder: 50,
  },
  {
    slug: "milkshakes-and-frappes",
    area: "cold-drinks",
    namePt: "Milkshakes e Frappés",
    descriptionPt: "400 ml de bebidas cremosas, ideais para sobremesa ou lanche.",
    accentColor: "var(--tone-berry)",
    sortOrder: 60,
  },
];

export const catalogProducts: CatalogProductSeed[] = [
  {
    slug: "coxinha-catupiry",
    categorySlug: "fried-savories",
    namePt: "Coxinha de Catupiry",
    descriptionPt: "Salgado frito clássico, cremoso por dentro e crocante por fora.",
    price: 8,
    artTone: "amber",
  },
  {
    slug: "enrolado-salsicha",
    categorySlug: "fried-savories",
    namePt: "Enrolado de Salsicha",
    descriptionPt: "Lanche rápido para consumir na mesa, no totem ou no balcão.",
    price: 8,
    artTone: "amber",
  },
  {
    slug: "kibe",
    categorySlug: "fried-savories",
    namePt: "Kibe",
    descriptionPt: "Receita tradicional com casquinha crocante e sabor marcante.",
    price: 8,
    artTone: "mocha",
  },
  {
    slug: "risoles",
    categorySlug: "fried-savories",
    namePt: "Risoles",
    descriptionPt: "Salgado frito muito pedido para acompanhar cafés curtos.",
    price: 8,
    artTone: "cream",
  },
  {
    slug: "esfiha-carne",
    categorySlug: "baked-savories",
    namePt: "Esfiha de Carne",
    descriptionPt: "Esfiha assada com recheio tradicional e massa leve.",
    price: 9,
    artTone: "mocha",
  },
  {
    slug: "esfiha-presunto-queijo",
    categorySlug: "baked-savories",
    namePt: "Esfiha de Presunto e Queijo",
    descriptionPt: "Versão assada para pedidos rápidos no balcão.",
    price: 9,
    artTone: "cream",
  },
  {
    slug: "empadao-frango",
    categorySlug: "baked-savories",
    namePt: "Empadão de Frango",
    descriptionPt: "Massa amanteigada e recheio cremoso de frango.",
    price: 9,
    artTone: "amber",
  },
  {
    slug: "empadinha-frango",
    categorySlug: "baked-savories",
    namePt: "Empadinha de Frango",
    descriptionPt: "Porção individual, ótima para vitrines de giro rápido.",
    price: 8,
    artTone: "amber",
  },
  {
    slug: "empadinha-palmito",
    categorySlug: "baked-savories",
    namePt: "Empadinha de Palmito",
    descriptionPt: "Versão vegetariana assada e delicada.",
    price: 8,
    artTone: "forest",
  },
  {
    slug: "pao-de-queijo-pequeno",
    categorySlug: "cheese-bread",
    namePt: "Pão de Queijo Pequeno",
    descriptionPt: "Feito diariamente com queijo de Minas na Cafeteria AT.",
    price: 2,
    artTone: "cream",
    featured: true,
  },
  {
    slug: "pao-de-queijo-grande",
    categorySlug: "cheese-bread",
    namePt: "Pão de Queijo Grande",
    descriptionPt: "Versão maior para um lanche mais reforçado.",
    price: 3,
    artTone: "cream",
  },
  {
    slug: "misto-quente-oregano",
    categorySlug: "grilled-sandwiches",
    namePt: "Misto Quente com Orégano",
    descriptionPt: "Queijo derretido, presunto e toque de orégano.",
    price: 7,
    artTone: "amber",
  },
  {
    slug: "misto-quente-sem-oregano",
    categorySlug: "grilled-sandwiches",
    namePt: "Misto Quente sem Orégano",
    descriptionPt: "Versão clássica para quem prefere sabor mais neutro.",
    price: 7,
    artTone: "cream",
  },
  {
    slug: "misto-quente-duplo-oregano",
    categorySlug: "grilled-sandwiches",
    namePt: "Misto Quente Duplo com Orégano",
    descriptionPt: "Mais recheio e tostado por fora.",
    price: 9,
    artTone: "amber",
  },
  {
    slug: "misto-quente-duplo-sem-oregano",
    categorySlug: "grilled-sandwiches",
    namePt: "Misto Quente Duplo sem Orégano",
    descriptionPt: "Versão dupla para pedidos rápidos de lanche.",
    price: 9,
    artTone: "mocha",
  },
  {
    slug: "croissant-bacon",
    categorySlug: "savory-croissants",
    namePt: "Croissant Bacon",
    descriptionPt: "Bacon, queijo e tomate em um croissant amanteigado.",
    price: 18,
    artTone: "amber",
    highlightPt: "Mais pedido",
  },
  {
    slug: "croissant-bacon-egg",
    categorySlug: "savory-croissants",
    namePt: "Croissant Bacon Egg",
    descriptionPt: "Bacon, queijo, ovo, alface e tomate.",
    price: 20,
    artTone: "amber",
  },
  {
    slug: "croissant-misto-quente",
    categorySlug: "savory-croissants",
    namePt: "Croissant Misto Quente",
    descriptionPt: "Presunto, queijo, tomate e orégano.",
    price: 16,
    artTone: "cream",
  },
  {
    slug: "croissant-queijo-quente",
    categorySlug: "savory-croissants",
    namePt: "Croissant Queijo Quente",
    descriptionPt: "Queijo, requeijão, tomate e orégano.",
    price: 15,
    artTone: "cream",
  },
  {
    slug: "croissant-simples",
    categorySlug: "savory-croissants",
    namePt: "Croissant Simples",
    descriptionPt: "Versão básica para complementar cafés e chocolates.",
    price: 12,
    artTone: "mocha",
  },
  {
    slug: "croissant-crocante",
    categorySlug: "sweet-croissants",
    namePt: "Croissant Crocante",
    descriptionPt: "Nutella e Ovomaltine em uma combinação intensa.",
    price: 18,
    artTone: "berry",
  },
  {
    slug: "croissant-doce-de-leite-pacoca",
    categorySlug: "sweet-croissants",
    namePt: "Croissant Doce de Leite com Paçoca",
    descriptionPt: "Doce de leite cremoso com toque de paçoca.",
    price: 15,
    artTone: "berry",
  },
  {
    slug: "croissant-morango-nutella",
    categorySlug: "sweet-croissants",
    namePt: "Croissant Morango com Nutella",
    descriptionPt: "Morango fresco com creme de avelã.",
    price: 16,
    artTone: "berry",
  },
  {
    slug: "croissant-romeu-julieta",
    categorySlug: "sweet-croissants",
    namePt: "Croissant Romeu e Julieta",
    descriptionPt: "Goiabada com queijo em versão doce da casa.",
    price: 15,
    artTone: "cream",
  },
  {
    slug: "croissant-pistache",
    categorySlug: "sweet-croissants",
    namePt: "Croissant Pistache",
    descriptionPt: "Pistache com castanhas para um final de pedido especial.",
    price: 20,
    artTone: "forest",
  },
  {
    slug: "bolo-caseiro-chocolate-ninho",
    categorySlug: "desserts",
    namePt: "Bolo Caseiro Chocolate com Ninho",
    descriptionPt: "Fatia generosa de bolo caseiro.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "bolo-caseiro-cenoura-chocolate",
    categorySlug: "desserts",
    namePt: "Bolo Caseiro Cenoura com Chocolate",
    descriptionPt: "Clássico de cafeteria para acompanhar cappuccino.",
    price: 10,
    artTone: "amber",
  },
  {
    slug: "bolo-caseiro-limao-raspas",
    categorySlug: "desserts",
    namePt: "Bolo Caseiro Limão com Raspas",
    descriptionPt: "Fresco e equilibrado para o turno da tarde.",
    price: 10,
    artTone: "forest",
  },
  {
    slug: "tapioca-americana",
    categorySlug: "tapiocas",
    namePt: "Tapioca Americana",
    descriptionPt: "Ovo, bacon e queijo.",
    price: 16,
    artTone: "amber",
  },
  {
    slug: "tapioca-misto-quente",
    categorySlug: "tapiocas",
    namePt: "Tapioca Misto Quente",
    descriptionPt: "Queijo, requeijão, tomate e orégano.",
    price: 15,
    artTone: "cream",
  },
  {
    slug: "tapioca-crocante",
    categorySlug: "tapiocas",
    namePt: "Tapioca Crocante",
    descriptionPt: "Nutella e Ovomaltine.",
    price: 18,
    artTone: "berry",
  },
  {
    slug: "tapioca-desejo",
    categorySlug: "tapiocas",
    namePt: "Tapioca Desejo",
    descriptionPt: "Morango com leite condensado.",
    price: 15,
    artTone: "berry",
  },
  {
    slug: "tapioca-mineira",
    categorySlug: "tapiocas",
    namePt: "Tapioca Mineira",
    descriptionPt: "Banana com doce de leite.",
    price: 12,
    artTone: "cream",
  },
  {
    slug: "tapioca-moca",
    categorySlug: "tapiocas",
    namePt: "Tapioca Moça",
    descriptionPt: "Leite condensado e queijo.",
    price: 13,
    artTone: "cream",
  },
  {
    slug: "tapioca-pecado",
    categorySlug: "tapiocas",
    namePt: "Tapioca Pecado",
    descriptionPt: "Morango com Nutella.",
    price: 18,
    artTone: "berry",
  },
  {
    slug: "crepioca-simples",
    categorySlug: "crepiocas",
    namePt: "Crepioca Simples",
    descriptionPt: "Queijo e presunto em crepe de tapioca com ovos.",
    price: 12,
    artTone: "cream",
  },
  {
    slug: "crepioca-americana",
    categorySlug: "crepiocas",
    namePt: "Crepioca Americana",
    descriptionPt: "Ovo, bacon e queijo.",
    price: 16,
    artTone: "amber",
  },
  {
    slug: "crepioca-misto-quente",
    categorySlug: "crepiocas",
    namePt: "Crepioca Misto Quente",
    descriptionPt: "Presunto, queijo, tomate e orégano.",
    price: 14,
    artTone: "mocha",
  },
  {
    slug: "crepioca-queijo-quente",
    categorySlug: "crepiocas",
    namePt: "Crepioca Queijo Quente",
    descriptionPt: "Queijo, requeijão, tomate e orégano. Preço a confirmar.",
    price: null,
    available: false,
    artTone: "cream",
    highlightPt: "Preço pendente",
  },
  {
    slug: "espresso-pequeno",
    categorySlug: "espresso-bar",
    namePt: "Café Espresso Pequeno",
    descriptionPt: "50 ml de espresso encorpado com aroma de chocolate.",
    price: 5,
    artTone: "mocha",
    featured: true,
  },
  {
    slug: "espresso-grande",
    categorySlug: "espresso-bar",
    namePt: "Café Espresso Grande",
    descriptionPt: "180 ml para quem quer um café mais longo.",
    price: 10,
    artTone: "mocha",
  },
  {
    slug: "canelinha",
    categorySlug: "espresso-bar",
    namePt: "Canelinha",
    descriptionPt: "Servido com canela em pó.",
    price: 5.5,
    artTone: "amber",
  },
  {
    slug: "espresso-com-leite",
    categorySlug: "espresso-bar",
    namePt: "Espresso com Leite",
    descriptionPt: "Um shot de café espresso e leite vaporizado.",
    price: 6,
    artTone: "cream",
  },
  {
    slug: "machiato",
    categorySlug: "espresso-bar",
    namePt: "Machiato",
    descriptionPt: "Espresso com espuma de leite.",
    price: 6,
    artTone: "cream",
  },
  {
    slug: "machiato-duplo",
    categorySlug: "espresso-bar",
    namePt: "Machiato Duplo",
    descriptionPt: "Dois shots de espresso e espuma de leite. Preço a confirmar.",
    price: null,
    available: false,
    artTone: "cream",
    highlightPt: "Preço pendente",
  },
  {
    slug: "cafe-coado",
    categorySlug: "espresso-bar",
    namePt: "Café Coado",
    descriptionPt: "Café coado da casa.",
    price: 4,
    artTone: "mocha",
  },
  {
    slug: "french-press",
    categorySlug: "espresso-bar",
    namePt: "French Press",
    descriptionPt:
      "295 ml de café em método de infusão e filtragem por pressão, resultando em bebida encorpada e aromática.",
    price: 15,
    artTone: "mocha",
  },
  {
    slug: "hario-v60",
    categorySlug: "espresso-bar",
    namePt: "Hario V60",
    descriptionPt:
      "180 ml em método com filtro de papel para uma bebida equilibrada com grãos acima de 80 pontos.",
    price: 10,
    artTone: "forest",
  },
  {
    slug: "cha-maca-verde",
    categorySlug: "teas",
    namePt: "Chá de Maçã Verde",
    descriptionPt: "180 ml servido quente.",
    price: 6,
    artTone: "forest",
  },
  {
    slug: "cha-pessego",
    categorySlug: "teas",
    namePt: "Chá de Pêssego",
    descriptionPt: "180 ml servido quente.",
    price: 6,
    artTone: "amber",
  },
  {
    slug: "cha-limao",
    categorySlug: "teas",
    namePt: "Chá de Limão",
    descriptionPt: "180 ml servido quente.",
    price: 6,
    artTone: "cream",
  },
  {
    slug: "cha-frutas-vermelhas",
    categorySlug: "teas",
    namePt: "Chá de Frutas Vermelhas",
    descriptionPt: "180 ml servido quente.",
    price: 6,
    artTone: "berry",
  },
  {
    slug: "cappuccino-belga",
    categorySlug: "cappuccinos",
    namePt: "Cappuccino com Chocolate Belga",
    descriptionPt: "Café, chocolate belga, leite vaporizado e canela.",
    price: 10,
    artTone: "cream",
  },
  {
    slug: "cappuccino-chantilly",
    categorySlug: "cappuccinos",
    namePt: "Cappuccino com Chantilly",
    descriptionPt: "Café espresso, chantilly e canela em pó.",
    price: 12,
    artTone: "cream",
  },
  {
    slug: "caramelow",
    categorySlug: "signature-hot-drinks",
    namePt: "Caramelow",
    descriptionPt: "Café espresso com espuma de leite e caramelo. Preço a confirmar.",
    price: null,
    available: false,
    artTone: "amber",
    highlightPt: "Preço pendente",
  },
  {
    slug: "mocha-chocolate",
    categorySlug: "signature-hot-drinks",
    namePt: "Mocha de Chocolate",
    descriptionPt: "Espresso, leite vaporizado e sabor chocolate.",
    price: 14,
    artTone: "berry",
  },
  {
    slug: "mocha-caramelo",
    categorySlug: "signature-hot-drinks",
    namePt: "Mocha de Caramelo",
    descriptionPt: "Espresso, leite vaporizado e sabor caramelo.",
    price: 14,
    artTone: "amber",
  },
  {
    slug: "mocha-leite-condensado",
    categorySlug: "signature-hot-drinks",
    namePt: "Mocha de Leite Condensado",
    descriptionPt: "Espresso, leite vaporizado e doçura cremosa.",
    price: 14,
    artTone: "cream",
  },
  {
    slug: "ovomaltine-leite-condensado",
    categorySlug: "signature-hot-drinks",
    namePt: "Ovomaltine com Leite Condensado",
    descriptionPt: "Bebida quente intensa e indulgente.",
    price: 16,
    artTone: "berry",
  },
  {
    slug: "chocolate-quente",
    categorySlug: "chocolates",
    namePt: "Chocolate Quente",
    descriptionPt: "Chocolate 50% cacau preparado com leite.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "shake-gelado-chocolate",
    categorySlug: "chocolates",
    namePt: "Shake Gelado de Chocolate",
    descriptionPt: "295 ml com Ovomaltine, canela e chantilly.",
    price: 15,
    artTone: "berry",
  },
  {
    slug: "choco-max-nutella",
    categorySlug: "chocolates",
    namePt: "Choco Max Nutella",
    descriptionPt:
      "Taça de chocolate gelado com borda de Nutella, calda de chocolate e chantilly com Ovomaltine.",
    price: 20,
    artTone: "berry",
    featured: true,
  },
  {
    slug: "coffee-caramelo-salgado",
    categorySlug: "iced-coffees",
    namePt: "Coffee Caramelo Salgado",
    descriptionPt: "Gelo, leite vaporizado e um shot de espresso.",
    price: 12,
    artTone: "amber",
  },
  {
    slug: "coffee-baunilha",
    categorySlug: "iced-coffees",
    namePt: "Coffee Baunilha",
    descriptionPt: "Versão gelada com espresso e toque de baunilha.",
    price: 12,
    artTone: "cream",
  },
  {
    slug: "coffee-shake-oreo-tradicional",
    categorySlug: "iced-coffees",
    namePt: "Coffee Shake Oreo Tradicional",
    descriptionPt: "Bolacha Oreo, leite, mousse de café solúvel, chantilly e gelo.",
    price: 18,
    artTone: "mocha",
  },
  {
    slug: "coffee-shake-oreo-selena",
    categorySlug: "iced-coffees",
    namePt: "Coffee Shake Oreo Selena",
    descriptionPt: "Variação com Oreo Selena, mousse de café e chantilly.",
    price: 18,
    artTone: "berry",
  },
  {
    slug: "afogatto",
    categorySlug: "iced-coffees",
    namePt: "Afogatto",
    descriptionPt: "Sorvete imerso em um shot duplo de café espresso.",
    price: 13,
    artTone: "cream",
  },
  {
    slug: "cappuccino-ice",
    categorySlug: "iced-coffees",
    namePt: "Cappuccino Ice",
    descriptionPt: "Versão refrescante com chantilly, calda de chocolate e canela.",
    price: 15,
    artTone: "cream",
  },
  {
    slug: "cha-batido-maca-verde",
    categorySlug: "cold-teas-and-lemonade",
    namePt: "Chá Batido Maçã Verde",
    descriptionPt: "400 ml com água com gás.",
    price: 8,
    artTone: "forest",
  },
  {
    slug: "cha-batido-limao",
    categorySlug: "cold-teas-and-lemonade",
    namePt: "Chá Batido Limão",
    descriptionPt: "400 ml com água com gás.",
    price: 8,
    artTone: "cream",
  },
  {
    slug: "cha-batido-pessego",
    categorySlug: "cold-teas-and-lemonade",
    namePt: "Chá Batido Pêssego",
    descriptionPt: "400 ml com água com gás.",
    price: 8,
    artTone: "amber",
  },
  {
    slug: "cha-batido-frutas-vermelhas",
    categorySlug: "cold-teas-and-lemonade",
    namePt: "Chá Batido Frutas Vermelhas",
    descriptionPt: "400 ml com água com gás.",
    price: 8,
    artTone: "berry",
  },
  {
    slug: "limonada-suica",
    categorySlug: "cold-teas-and-lemonade",
    namePt: "Limonada Suíça",
    descriptionPt: "400 ml com leite condensado.",
    price: 12,
    artTone: "forest",
  },
  {
    slug: "soda-limao-siciliano",
    categorySlug: "sodas",
    namePt: "Soda Limão Siciliano",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "cream",
  },
  {
    slug: "soda-maca-verde",
    categorySlug: "sodas",
    namePt: "Soda Maçã Verde",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "forest",
  },
  {
    slug: "soda-blue-lemonade",
    categorySlug: "sodas",
    namePt: "Soda Blue Lemonade",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "berry",
  },
  {
    slug: "soda-pink-lemonade",
    categorySlug: "sodas",
    namePt: "Soda Pink Lemonade",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "berry",
  },
  {
    slug: "soda-cha-mate-tostado",
    categorySlug: "sodas",
    namePt: "Soda Chá Mate Tostado",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "mocha",
  },
  {
    slug: "soda-framboesa",
    categorySlug: "sodas",
    namePt: "Soda Framboesa",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "berry",
  },
  {
    slug: "soda-tangerina-gengibre",
    categorySlug: "sodas",
    namePt: "Soda Tangerina e Gengibre",
    descriptionPt: "Soda artesanal 400 ml.",
    price: 11,
    artTone: "amber",
  },
  {
    slug: "refrigerante-mini",
    categorySlug: "cold-beverages",
    namePt: "Refrigerante Mini",
    descriptionPt: "Versão compacta para pedidos rápidos.",
    price: 3,
    artTone: "cream",
  },
  {
    slug: "refrigerante-lata",
    categorySlug: "cold-beverages",
    namePt: "Refrigerante Lata",
    descriptionPt: "Lata gelada pronta para entrega.",
    price: 6,
    artTone: "cream",
  },
  {
    slug: "coca-cola-ks",
    categorySlug: "cold-beverages",
    namePt: "Coca-Cola KS",
    descriptionPt: "Garrafa individual tradicional.",
    price: 6.5,
    artTone: "berry",
  },
  {
    slug: "coca-cola-2l",
    categorySlug: "cold-beverages",
    namePt: "Coca-Cola 2 Litros",
    descriptionPt: "Ideal para dividir entre grupos.",
    price: 14,
    artTone: "berry",
  },
  {
    slug: "pepsi-2l",
    categorySlug: "cold-beverages",
    namePt: "Pepsi 2 Litros",
    descriptionPt: "Garrafa para pedidos em grupo.",
    price: 12,
    artTone: "berry",
  },
  {
    slug: "fanta-2l",
    categorySlug: "cold-beverages",
    namePt: "Fanta 2 Litros",
    descriptionPt: "Garrafa para pedidos em grupo.",
    price: 12,
    artTone: "amber",
  },
  {
    slug: "cha-mate-com-gas",
    categorySlug: "cold-beverages",
    namePt: "Chá Mate com Gás",
    descriptionPt: "Opção pronta e gelada.",
    price: 7,
    artTone: "forest",
  },
  {
    slug: "del-valle-lata",
    categorySlug: "cold-beverages",
    namePt: "Del Valle Lata",
    descriptionPt: "Suco pronto gelado.",
    price: 6.5,
    artTone: "amber",
  },
  {
    slug: "del-valle-garrafa",
    categorySlug: "cold-beverages",
    namePt: "Del Valle Garrafa",
    descriptionPt: "Versão individual em garrafa.",
    price: 6,
    artTone: "amber",
  },
  {
    slug: "kapo",
    categorySlug: "cold-beverages",
    namePt: "Kapo",
    descriptionPt: "Suco prático para pedidos rápidos.",
    price: 4.5,
    artTone: "amber",
  },
  {
    slug: "suco-caixinha",
    categorySlug: "cold-beverages",
    namePt: "Suco de Caixinha",
    descriptionPt: "Disponível conforme estoque da geladeira.",
    price: 4,
    artTone: "amber",
  },
  {
    slug: "achocolatado",
    categorySlug: "cold-beverages",
    namePt: "Achocolatado",
    descriptionPt: "Pronto para consumo.",
    price: 2.5,
    artTone: "cream",
  },
  {
    slug: "suco-lata-com-gas",
    categorySlug: "cold-beverages",
    namePt: "Suco Lata com Gás",
    descriptionPt: "Versão gaseificada gelada.",
    price: 7.5,
    artTone: "forest",
  },
  {
    slug: "gatorade",
    categorySlug: "cold-beverages",
    namePt: "Gatorade",
    descriptionPt: "Reposição rápida para dias quentes.",
    price: 7.5,
    artTone: "forest",
  },
  {
    slug: "monster",
    categorySlug: "cold-beverages",
    namePt: "Monster",
    descriptionPt: "Energético em lata.",
    price: 12,
    artTone: "forest",
  },
  {
    slug: "red-bull",
    categorySlug: "cold-beverages",
    namePt: "Red Bull",
    descriptionPt: "Energético em lata.",
    price: 11,
    artTone: "berry",
  },
  {
    slug: "baly",
    categorySlug: "cold-beverages",
    namePt: "Baly",
    descriptionPt: "Energético gelado.",
    price: 9,
    artTone: "berry",
  },
  {
    slug: "furioso",
    categorySlug: "cold-beverages",
    namePt: "Furioso",
    descriptionPt: "Opção econômica de energético.",
    price: 4.5,
    artTone: "berry",
  },
  {
    slug: "cha-mate-copo",
    categorySlug: "cold-beverages",
    namePt: "Chá Mate Copo",
    descriptionPt: "Versão pronta para balcão.",
    price: 4.5,
    artTone: "forest",
  },
  {
    slug: "mini-cini",
    categorySlug: "cold-beverages",
    namePt: "Mini Cini",
    descriptionPt: "Refrigerante individual.",
    price: 2,
    artTone: "amber",
  },
  {
    slug: "cini-mix",
    categorySlug: "cold-beverages",
    namePt: "Cini Mix",
    descriptionPt: "Versão prática e gelada.",
    price: 3.5,
    artTone: "amber",
  },
  {
    slug: "agua-mineral-sem-gas",
    categorySlug: "cold-beverages",
    namePt: "Água Mineral sem Gás",
    descriptionPt: "Garrafa individual.",
    price: 2.5,
    artTone: "cream",
  },
  {
    slug: "agua-mineral-com-gas",
    categorySlug: "cold-beverages",
    namePt: "Água Mineral com Gás",
    descriptionPt: "Garrafa individual.",
    price: 2.5,
    artTone: "cream",
  },
  {
    slug: "agua-saborizada",
    categorySlug: "cold-beverages",
    namePt: "Água Saborizada",
    descriptionPt: "Leve e refrescante.",
    price: 4.5,
    artTone: "forest",
  },
  {
    slug: "suco-natural-laranja",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Laranja",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "amber",
  },
  {
    slug: "suco-natural-abacaxi",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Abacaxi",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "forest",
  },
  {
    slug: "suco-natural-limao",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Limão",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "cream",
  },
  {
    slug: "suco-natural-morango",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Morango",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "suco-natural-mamao",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Mamão",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "amber",
  },
  {
    slug: "suco-natural-melao",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Melão",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "cream",
  },
  {
    slug: "suco-natural-melancia",
    categorySlug: "juices-and-vitaminas",
    namePt: "Suco Natural de Melancia",
    descriptionPt: "400 ml de fruta natural.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "polpa-abacaxi-hortela",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida Abacaxi com Hortelã",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "forest",
  },
  {
    slug: "polpa-acerola",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Acerola",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "polpa-coco",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Coco",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "cream",
  },
  {
    slug: "polpa-manga",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Manga",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "amber",
  },
  {
    slug: "polpa-maracuja",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Maracujá",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "amber",
  },
  {
    slug: "polpa-melancia",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Melancia",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "polpa-morango",
    categorySlug: "juices-and-vitaminas",
    namePt: "Polpa Batida de Morango",
    descriptionPt: "Batido com água.",
    price: 10,
    artTone: "berry",
  },
  {
    slug: "vitamina-banana-maca",
    categorySlug: "juices-and-vitaminas",
    namePt: "Vitamina Banana com Maçã",
    descriptionPt: "400 ml batidos na hora.",
    price: 16,
    artTone: "cream",
  },
  {
    slug: "milkshake-morango",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Milkshake de Morango",
    descriptionPt: "400 ml cremosos.",
    price: 16,
    artTone: "berry",
  },
  {
    slug: "milkshake-creme",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Milkshake de Creme",
    descriptionPt: "400 ml cremosos.",
    price: 16,
    artTone: "cream",
  },
  {
    slug: "milkshake-chocolate",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Milkshake de Chocolate",
    descriptionPt: "400 ml cremosos.",
    price: 16,
    artTone: "mocha",
  },
  {
    slug: "milkshake-ovomaltine",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Milkshake de Ovomaltine",
    descriptionPt: "400 ml cremosos.",
    price: 16,
    artTone: "berry",
  },
  {
    slug: "frappe-cafe",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Frapê de Café",
    descriptionPt: "400 ml gelados.",
    price: 15,
    artTone: "mocha",
  },
  {
    slug: "frappe-morango",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Frapê de Morango",
    descriptionPt: "400 ml gelados.",
    price: 15,
    artTone: "berry",
  },
  {
    slug: "frappe-chocolate",
    categorySlug: "milkshakes-and-frappes",
    namePt: "Frapê de Chocolate",
    descriptionPt: "400 ml gelados.",
    price: 15,
    artTone: "mocha",
  },
];

export const demoOrders = [
  {
    id: "demo-order-1",
    displayCode: "AT-241",
    customerName: "Mesa 04 - Carla",
    channel: "TABLE",
    status: "IN_QUEUE",
    paymentStatus: "PAID",
    paymentMethod: "PIX",
    requiresCounterPayment: false,
    canStartPreparation: true,
    total: 35,
    createdAt: new Date().toISOString(),
    items: [
      { id: "item-1", name: "Croissant Bacon", quantity: 1, unitPrice: 18, notes: null },
      { id: "item-2", name: "Cappuccino Ice", quantity: 1, unitPrice: 15, notes: null },
    ],
  },
  {
    id: "demo-order-2",
    displayCode: "AT-242",
    customerName: "Rafael",
    channel: "COUNTER",
    status: "AWAITING_PAYMENT",
    paymentStatus: "PENDING",
    paymentMethod: "PAY_AT_COUNTER",
    requiresCounterPayment: true,
    canStartPreparation: false,
    total: 20,
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    items: [{ id: "item-3", name: "Bacon Egg", quantity: 1, unitPrice: 20, notes: null }],
  },
  {
    id: "demo-order-3",
    displayCode: "AT-239",
    customerName: "Mesa 02 - Bruno",
    channel: "TABLE",
    status: "PREPARING",
    paymentStatus: "PAID",
    paymentMethod: "ONLINE_CARD",
    requiresCounterPayment: false,
    canStartPreparation: true,
    total: 25,
    createdAt: new Date(Date.now() - 1000 * 60 * 19).toISOString(),
    items: [
      { id: "item-4", name: "Espresso Grande", quantity: 1, unitPrice: 10, notes: null },
      { id: "item-5", name: "Tapioca Americana", quantity: 1, unitPrice: 16, notes: null },
    ],
  },
];

export const demoInventoryMovements = [
  {
    id: "movement-1",
    titlePt: "Compra de leite",
    type: "PURCHASE",
    quantity: 24,
    unitLabel: "litros",
    totalAmount: 198,
    happenedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "movement-2",
    titlePt: "Entrada de grãos arábica",
    type: "ENTRY",
    quantity: 6,
    unitLabel: "kg",
    totalAmount: 0,
    happenedAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
  },
];

export const demoFinanceEntries = [
  {
    id: "finance-1",
    direction: "INCOME",
    category: "SALE",
    descriptionPt: "Vendas do turno da manhã",
    amount: 486.5,
    happenedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    id: "finance-2",
    direction: "EXPENSE",
    category: "SUPPLY_PURCHASE",
    descriptionPt: "Compra de leite e embalagens",
    amount: 198,
    happenedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];
